version: "3.3"
services:
  relay:
    build: node-qstat-relay
    restart: always
    container_name: node-qstat-relay
    volumes:
      - ".:/app"
    # ports:
    #   - "5000:3000"
    #   - "27015:27015"
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8181:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
  api:
    environment:
      DB_HOST: mongodb://root:root@mongo:27017/fragworld-browser?authSource=admin
    build: .
    container_name: server-browser-api
    links:
      - mongo
      - relay
    volumes:
      - ".:/app"
    ports:
      - "3003:3000"
    restart: always
