version: "3.3"
services:
  relay:
    build: node-qstat-relay/
    restart: always
    container_name: node-qstat-relay
    volumes:
      - "./node-qstat-relay:/app"
  mongo:
    image: mongo
    restart: always
    volumes:
      - "./db:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8181:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
  # webapp:
  #   build: rcon-ui/
  #   container_name: "webapp"
  #   volumes:
  #     - "./rcon-ui:/app"
  #   environment:
  #     - NODE_ENV=production
  #     - REACT_APP_PROXY=https://panel.frag.world/api/
  nginx:
    image: "nginx:alpine"
    container_name: frontproxy
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "/root/certs:/etc/nginx/certs"
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
    links:
      - api
  api:
    build: .
    command: "npm start"
    volumes:
      - ".:/app"
    links:
      - mongo
      - relay
    ports:
      - "3003:3000"
    environment:
      DB_HOST: mongodb://root:root@mongo:27017/fragworld-browser?authSource=admin
      RELAY_URL: http://relay:3000/
      CORS_ORIGIN: "https://ys647.csb.app"
    container_name: server-browser-api
volumes:
  redis:
