version: "3.3"
services:
  relay:
    build: node-qstat-relay/
    restart: always
    container_name: node-qstat-relay
    volumes:
      - "./node-qstat-relay:/app"
    logging:
      driver: none
  mongo:
    image: mongo:4.0
    restart: always
    volumes:
      - "./db/data:/data/db"
      - "./db/migrations:/db/migrations"
      - "./db/seed:/db/seed"
      - "./db/scripts:/db/scripts"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    logging:
      driver: none
  users-service:
    build: ./users-service
    container_name: users-service
    volumes:
      - "./users-service:/app"
    environment:
      DB_HOST: mongodb://root:root@mongo:27017/fragworld-users?authSource=admin
    links:
      - mongo
  favorites-service:
    build: ./favorites-service
    container_name: favorites-service
    volumes:
      - "./favorites-service:/app"
    environment:
      DB_HOST: mongodb://root:root@mongo:27017/fragworld-favorites?authSource=admin
    links:
      - mongo
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8181:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: root
  #     ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
  # webapp:
  #   build: rcon-ui/
  #   container_name: "webapp"
  #   volumes:
  #     - "./rcon-ui:/app"
  #   environment:
  #     - NODE_ENV=production
  #     - REACT_APP_PROXY=https://panel.frag.world/api/
  nginx:
    image: "nginx:alpine"
    container_name: frontproxy
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "/root/certs:/etc/nginx/certs"
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
    links:
      - api
    logging:
      driver: none
  api:
    build: .
    volumes:
      - ".:/app"
    links:
      - mongo
      - relay
      - users-service
      - favorites-service
    environment:
      DB_HOST: mongodb://root:root@mongo:27017/fragworld-browser?authSource=admin
      RELAY_URL: http://relay:3000/
      FAVORITES_SERVICE_URL: http://favorites-service:3000
      USERS_SERVICE_URL: http://users-service:3000
    container_name: server-browser-api
volumes:
  redis:
