version: "3.3"
services:
  relay:
    build: node-qstat-relay/
    restart: always
    container_name: node-qstat-relay
    volumes:
      - "./node-qstat-relay:/app"
    logging:
      driver: none
  mongo:
    image: mongo:4.0
    restart: always
    volumes:
      - "./db/data:/data/db"
      - "./db/migrations:/db/migrations"
      - "./db/seed:/db/seed"
      - "./db/scripts:/db/scripts"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    logging:
      driver: none
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8181:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
    logging:
      driver: none
  users-service:
    build: ./users-service
    container_name: users-service
    volumes:
      - "./users-service:/app"
    environment:
      DB_HOST: mongodb://root:root@mongo:27017/fragworld-users?authSource=admin
    links:
      - mongo
    logging:
      driver: none
  filter-config-service:
    build: ./filter-config-service
    container_name: filter-config-service
    volumes:
      - "./filter-config-service:/app"
    environment:
      DB_HOST: mongodb://root:root@mongo:27017/fragworld-filter-configs?authSource=admin
    links:
      - mongo
    # logging:
    #   driver: none
  rcon-relay:
    build: rcon-relay/
    container_name: rcon-relay
    volumes:
      - "./rcon-relay:/app"
    logging:
      driver: none
  favorites-service:
    build: ./favorites-service
    container_name: favorites-service
    volumes:
      - "./favorites-service:/app"
    environment:
      DB_HOST: mongodb://root:root@mongo:27017/fragworld-favorites?authSource=admin
    links:
      - mongo
    logging:
      driver: none
  # sessions-service:
  #   build: ./sessions-service
  #   container_name: sessions-service
  #   volumes:
  #     - "./sessions-service:/app"
  #   environment:
  #     DB_HOST: mongodb://root:root@mongo:6379
  #     USERS_SERVICE_URL: http://users-service:3000
  #   links:
  #     - redis
  #     - users-service
  # redis:
  #   image: "redis:alpine"
  #   restart: always
  #   command: redis-server --requirepass pass
  #   # ports:
  #   #  - "6379:6379"
  #   volumes:
  #     - ./sessions-service/redis/data:/var/lib/redis
  #       # - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
  #   environment:
  #     REDIS_REPLICATION_MODE: master
  webapp:
    build: fragworld-ui/
    container_name: "fragworld-ui"
    volumes:
      - "./fragworld-ui:/app"
    environment:
      - NODE_ENV=development
      - REACT_APP_PROXY=http://127.0.0.1:3003
    ports:
      - "3001:3000"
    logging:
      driver: none
    # command: /bin/bash -c "npm start"
  api:
    environment:
      DB_HOST: mongodb://root:root@mongo:27017/fragworld-browser?authSource=admin
      RELAY_URL: http://relay:3000/
      RCON_RELAY_URL: http://rcon-relay:3000/
      FAVORITES_SERVICE_URL: http://favorites-service:3000
      USERS_SERVICE_URL: http://users-service:3000
      FILTER_CONFIG_SERVICE_URL: http://filter-config-service:3000
      CORS_ORIGIN: http://127.0.0.1:3001
    build: .
    container_name: server-browser-api
    links:
      - mongo
      - relay
      - users-service
      - favorites-service
      - filter-config-service
      - rcon-relay
    volumes:
      - ".:/app"
    ports:
      - "3003:3000"
    restart: always
    # logging:
    #   driver: none
