version: "3.3"
services:
  relay:
    build: node-qstat-relay/
    restart: always
    container_name: node-qstat-relay
    volumes:
      - "./node-qstat-relay:/app"
  mongo:
    image: mongo
    restart: always
    volumes:
      - "./db/data:/data/db"
      - "./db/migrations:/db/migrations"
      - "./db/seed:/db/seed"
      - "./db/scripts:/db/scripts"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8181:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
  api:
    environment:
      DB_HOST: mongodb://root:root@mongo:27017/fragworld-browser?authSource=admin
      RELAY_URL: http://relay:3000/
      CORS_ORIGIN: "https://ys647.csb.app"
    build: .
    container_name: server-browser-api
    links:
      - mongo
      - relay
    volumes:
      - ".:/app"
    ports:
      - "3003:3000"
    restart: always
